# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Encryptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 288)
        self.encryptor_Folder = QtWidgets.QLineEdit(Form)
        self.encryptor_Folder.setGeometry(QtCore.QRect(72, 70, 351, 27))
        self.encryptor_Folder.setObjectName("encryptor_Folder")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 40, 351, 19))
        self.label.setObjectName("label")
        self.encryptor_Password = QtWidgets.QLineEdit(Form)
        self.encryptor_Password.setGeometry(QtCore.QRect(72, 150, 351, 27))
        self.encryptor_Password.setText("")
        self.encryptor_Password.setObjectName("encryptor_Password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 120, 351, 19))
        self.label_2.setObjectName("label_2")
        self.encryptor_EncryptButton = QtWidgets.QPushButton(Form)
        self.encryptor_EncryptButton.setGeometry(QtCore.QRect(190, 230, 101, 27))
        self.encryptor_EncryptButton.setObjectName("encryptor_EncryptButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 231, 19))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.encryptor_Folder.setPlaceholderText(_translate("Form", "/home/CompanyFiles/ImportantDocs"))
        self.label.setText(_translate("Form", "Folder/file To Encrypt (Encrypts all subfolders/files)"))
        self.encryptor_Password.setPlaceholderText(_translate("Form", "Something Strong, 10+ Characters"))
        self.label_2.setText(_translate("Form", "Password"))
        self.encryptor_EncryptButton.setText(_translate("Form", "Encrypt!"))
        self.label_3.setText(_translate("Form", "File Encryptor"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Encryptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(488, 321)
        self.encryptor_Folder = QtWidgets.QLineEdit(Form)
        self.encryptor_Folder.setGeometry(QtCore.QRect(72, 70, 351, 27))
        self.encryptor_Folder.setObjectName("encryptor_Folder")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 40, 351, 19))
        self.label.setObjectName("label")
        self.encryptor_Password = QtWidgets.QLineEdit(Form)
        self.encryptor_Password.setGeometry(QtCore.QRect(72, 220, 351, 27))
        self.encryptor_Password.setText("")
        self.encryptor_Password.setObjectName("encryptor_Password")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(70, 190, 351, 19))
        self.label_2.setObjectName("label_2")
        self.encryptor_EncryptButton = QtWidgets.QPushButton(Form)
        self.encryptor_EncryptButton.setGeometry(QtCore.QRect(190, 270, 101, 27))
        self.encryptor_EncryptButton.setObjectName("encryptor_EncryptButton")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 231, 19))
        self.label_3.setObjectName("label_3")
        self.encryptor_Extension = QtWidgets.QLineEdit(Form)
        self.encryptor_Extension.setGeometry(QtCore.QRect(70, 150, 351, 27))
        self.encryptor_Extension.setObjectName("encryptor_Extension")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(70, 120, 351, 19))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.encryptor_Folder.setPlaceholderText(_translate("Form", "/home/CompanyFiles/ImportantDocs"))
        self.label.setText(_translate("Form", "Folder/file To Encrypt (Encrypts all subfolders/files)"))
        self.encryptor_Password.setPlaceholderText(_translate("Form", "Something Strong, 10+ Characters"))
        self.label_2.setText(_translate("Form", "Password"))
        self.encryptor_EncryptButton.setText(_translate("Form", "Encrypt!"))
        self.label_3.setText(_translate("Form", "File Encryptor"))
        self.encryptor_Extension.setPlaceholderText(_translate("Form", "encrypted (No \'.\')"))
        self.label_4.setText(_translate("Form", "Encrypted File Extension"))
