# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listen_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listener_popup(object):
    def setupUi(self, listener_popup):
        listener_popup.setObjectName("listener_popup")
        listener_popup.resize(341, 269)
        self.centralwidget = QtWidgets.QWidget(listener_popup)
        self.centralwidget.setObjectName("centralwidget")
        self.popup_listen_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_ip.setGeometry(QtCore.QRect(70, 60, 191, 27))
        self.popup_listen_ip.setObjectName("popup_listen_ip")
        self.popup_listen_port = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_port.setGeometry(QtCore.QRect(70, 130, 191, 27))
        self.popup_listen_port.setObjectName("popup_listen_port")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 181, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 161, 19))
        self.label_2.setObjectName("label_2")
        self.popup_listen_LISTEN = QtWidgets.QPushButton(self.centralwidget)
        self.popup_listen_LISTEN.setGeometry(QtCore.QRect(120, 190, 87, 27))
        self.popup_listen_LISTEN.setObjectName("popup_listen_LISTEN")
        listener_popup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listener_popup)
        self.statusbar.setObjectName("statusbar")
        listener_popup.setStatusBar(self.statusbar)

        self.retranslateUi(listener_popup)
        QtCore.QMetaObject.connectSlotsByName(listener_popup)

    def retranslateUi(self, listener_popup):
        _translate = QtCore.QCoreApplication.translate
        listener_popup.setWindowTitle(_translate("listener_popup", "MainWindow"))
        self.popup_listen_ip.setPlaceholderText(_translate("listener_popup", "0.0.0.0"))
        self.label.setText(_translate("listener_popup", "IP to listen on"))
        self.label_2.setText(_translate("listener_popup", "Port to listen on "))
        self.popup_listen_LISTEN.setText(_translate("listener_popup", "Listen!"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listen_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listener_popup(object):
    def setupUi(self, listener_popup):
        listener_popup.setObjectName("listener_popup")
        listener_popup.resize(341, 269)
        self.centralwidget = QtWidgets.QWidget(listener_popup)
        self.centralwidget.setObjectName("centralwidget")
        self.popup_listen_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_ip.setGeometry(QtCore.QRect(70, 60, 191, 27))
        self.popup_listen_ip.setObjectName("popup_listen_ip")
        self.popup_listen_port = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_port.setGeometry(QtCore.QRect(70, 130, 191, 27))
        self.popup_listen_port.setObjectName("popup_listen_port")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 181, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 161, 19))
        self.label_2.setObjectName("label_2")
        self.popup_listen_LISTEN = QtWidgets.QPushButton(self.centralwidget)
        self.popup_listen_LISTEN.setGeometry(QtCore.QRect(120, 190, 87, 27))
        self.popup_listen_LISTEN.setObjectName("popup_listen_LISTEN")
        listener_popup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listener_popup)
        self.statusbar.setObjectName("statusbar")
        listener_popup.setStatusBar(self.statusbar)

        self.retranslateUi(listener_popup)
        QtCore.QMetaObject.connectSlotsByName(listener_popup)

    def retranslateUi(self, listener_popup):
        _translate = QtCore.QCoreApplication.translate
        listener_popup.setWindowTitle(_translate("listener_popup", "MainWindow"))
        self.popup_listen_ip.setPlaceholderText(_translate("listener_popup", "0.0.0.0"))
        self.popup_listen_port.setPlaceholderText(_translate("listener_popup", "12345"))
        self.label.setText(_translate("listener_popup", "IP to listen on"))
        self.label_2.setText(_translate("listener_popup", "Port to listen on "))
        self.popup_listen_LISTEN.setText(_translate("listener_popup", "Listen!"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'listen_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_listener_popup(object):
    def setupUi(self, listener_popup):
        listener_popup.setObjectName("listener_popup")
        listener_popup.resize(341, 269)
        self.centralwidget = QtWidgets.QWidget(listener_popup)
        self.centralwidget.setObjectName("centralwidget")
        self.popup_listen_ip = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_ip.setGeometry(QtCore.QRect(70, 60, 191, 27))
        self.popup_listen_ip.setObjectName("popup_listen_ip")
        self.popup_listen_port = QtWidgets.QLineEdit(self.centralwidget)
        self.popup_listen_port.setGeometry(QtCore.QRect(70, 130, 191, 27))
        self.popup_listen_port.setObjectName("popup_listen_port")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(70, 40, 181, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 110, 161, 19))
        self.label_2.setObjectName("label_2")
        self.popup_listen_LISTEN = QtWidgets.QPushButton(self.centralwidget)
        self.popup_listen_LISTEN.setGeometry(QtCore.QRect(120, 190, 87, 27))
        self.popup_listen_LISTEN.setObjectName("popup_listen_LISTEN")
        listener_popup.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(listener_popup)
        self.statusbar.setObjectName("statusbar")
        listener_popup.setStatusBar(self.statusbar)

        self.retranslateUi(listener_popup)
        QtCore.QMetaObject.connectSlotsByName(listener_popup)

    def retranslateUi(self, listener_popup):
        _translate = QtCore.QCoreApplication.translate
        listener_popup.setWindowTitle(_translate("listener_popup", "MainWindow"))
        self.popup_listen_ip.setPlaceholderText(_translate("listener_popup", "0.0.0.0"))
        self.popup_listen_port.setPlaceholderText(_translate("listener_popup", "12345"))
        self.label.setText(_translate("listener_popup", "IP to listen on"))
        self.label_2.setText(_translate("listener_popup", "Port to listen on "))
        self.popup_listen_LISTEN.setText(_translate("listener_popup", "Listen!"))
