# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portscan_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PortScan_Popup(object):
    def setupUi(self, PortScan_Popup):
        PortScan_Popup.setObjectName("PortScan_Popup")
        PortScan_Popup.resize(350, 425)
        self.portscan_IP = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_IP.setGeometry(QtCore.QRect(50, 40, 250, 25))
        self.portscan_IP.setObjectName("portscan_IP")
        self.portscan_minport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_minport.setGeometry(QtCore.QRect(50, 100, 100, 25))
        self.portscan_minport.setObjectName("portscan_minport")
        self.portscan_maxport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_maxport.setGeometry(QtCore.QRect(200, 100, 100, 25))
        self.portscan_maxport.setObjectName("portscan_maxport")
        self.portscan_extraport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_extraport.setGeometry(QtCore.QRect(50, 190, 250, 25))
        self.portscan_extraport.setObjectName("portscan_extraport")
        self.label = QtWidgets.QLabel(PortScan_Popup)
        self.label.setGeometry(QtCore.QRect(50, 20, 66, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PortScan_Popup)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 66, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PortScan_Popup)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 66, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PortScan_Popup)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 51, 19))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(PortScan_Popup)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 301, 20))
        self.label_5.setObjectName("label_5")
        self.portscan_standard_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_standard_check.setGeometry(QtCore.QRect(50, 280, 92, 25))
        self.portscan_standard_check.setObjectName("portscan_standard_check")
        self.label_6 = QtWidgets.QLabel(PortScan_Popup)
        self.label_6.setGeometry(QtCore.QRect(140, 240, 161, 19))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 310, 92, 25))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_3.setGeometry(QtCore.QRect(225, 310, 92, 25))
        self.checkBox_3.setObjectName("checkBox_3")
        self.portscan_stealth_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_stealth_check.setGeometry(QtCore.QRect(225, 280, 92, 25))
        self.portscan_stealth_check.setObjectName("portscan_stealth_check")
        self.portscan_start = QtWidgets.QPushButton(PortScan_Popup)
        self.portscan_start.setGeometry(QtCore.QRect(50, 380, 251, 27))
        self.portscan_start.setObjectName("portscan_start")

        self.retranslateUi(PortScan_Popup)
        QtCore.QMetaObject.connectSlotsByName(PortScan_Popup)

    def retranslateUi(self, PortScan_Popup):
        _translate = QtCore.QCoreApplication.translate
        PortScan_Popup.setWindowTitle(_translate("PortScan_Popup", "Form"))
        self.portscan_IP.setPlaceholderText(_translate("PortScan_Popup", "8.8.8.8"))
        self.portscan_minport.setPlaceholderText(_translate("PortScan_Popup", "1"))
        self.portscan_maxport.setPlaceholderText(_translate("PortScan_Popup", "1024"))
        self.portscan_extraport.setPlaceholderText(_translate("PortScan_Popup", "80, 443"))
        self.label.setText(_translate("PortScan_Popup", "Target IP"))
        self.label_2.setText(_translate("PortScan_Popup", "Min Port"))
        self.label_3.setText(_translate("PortScan_Popup", "Max Port"))
        self.label_4.setText(_translate("PortScan_Popup", "And/Or"))
        self.label_5.setText(_translate("PortScan_Popup", "Specific ports"))
        self.portscan_standard_check.setText(_translate("PortScan_Popup", "Standard"))
        self.label_6.setText(_translate("PortScan_Popup", "Scan Type"))
        self.checkBox_2.setText(_translate("PortScan_Popup", "Other1"))
        self.checkBox_3.setText(_translate("PortScan_Popup", "Other2"))
        self.portscan_stealth_check.setText(_translate("PortScan_Popup", "Stealth"))
        self.portscan_start.setText(_translate("PortScan_Popup", "-->> Start Scan <<--"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portscan_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PortScan_Popup(object):
    def setupUi(self, PortScan_Popup):
        PortScan_Popup.setObjectName("PortScan_Popup")
        PortScan_Popup.resize(350, 425)
        self.portscan_IP = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_IP.setGeometry(QtCore.QRect(50, 40, 250, 25))
        self.portscan_IP.setObjectName("portscan_IP")
        self.portscan_minport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_minport.setGeometry(QtCore.QRect(50, 100, 100, 25))
        self.portscan_minport.setObjectName("portscan_minport")
        self.portscan_maxport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_maxport.setGeometry(QtCore.QRect(200, 100, 100, 25))
        self.portscan_maxport.setObjectName("portscan_maxport")
        self.portscan_extraport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_extraport.setGeometry(QtCore.QRect(50, 190, 250, 25))
        self.portscan_extraport.setObjectName("portscan_extraport")
        self.label = QtWidgets.QLabel(PortScan_Popup)
        self.label.setGeometry(QtCore.QRect(50, 20, 66, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PortScan_Popup)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 66, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PortScan_Popup)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 66, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PortScan_Popup)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 51, 19))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(PortScan_Popup)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 301, 20))
        self.label_5.setObjectName("label_5")
        self.portscan_standard_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_standard_check.setGeometry(QtCore.QRect(50, 280, 92, 25))
        self.portscan_standard_check.setObjectName("portscan_standard_check")
        self.label_6 = QtWidgets.QLabel(PortScan_Popup)
        self.label_6.setGeometry(QtCore.QRect(140, 240, 161, 19))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 310, 92, 25))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_3.setGeometry(QtCore.QRect(225, 310, 92, 25))
        self.checkBox_3.setObjectName("checkBox_3")
        self.portscan_stealth_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_stealth_check.setGeometry(QtCore.QRect(225, 280, 92, 25))
        self.portscan_stealth_check.setObjectName("portscan_stealth_check")
        self.portscan_start = QtWidgets.QPushButton(PortScan_Popup)
        self.portscan_start.setGeometry(QtCore.QRect(50, 380, 251, 27))
        self.portscan_start.setObjectName("portscan_start")

        self.retranslateUi(PortScan_Popup)
        QtCore.QMetaObject.connectSlotsByName(PortScan_Popup)

    def retranslateUi(self, PortScan_Popup):
        _translate = QtCore.QCoreApplication.translate
        PortScan_Popup.setWindowTitle(_translate("PortScan_Popup", "PortScan"))
        self.portscan_IP.setPlaceholderText(_translate("PortScan_Popup", "8.8.8.8"))
        self.portscan_minport.setPlaceholderText(_translate("PortScan_Popup", "1"))
        self.portscan_maxport.setPlaceholderText(_translate("PortScan_Popup", "1024"))
        self.portscan_extraport.setPlaceholderText(_translate("PortScan_Popup", "80, 443"))
        self.label.setText(_translate("PortScan_Popup", "Target IP"))
        self.label_2.setText(_translate("PortScan_Popup", "Min Port"))
        self.label_3.setText(_translate("PortScan_Popup", "Max Port"))
        self.label_4.setText(_translate("PortScan_Popup", "And/Or"))
        self.label_5.setText(_translate("PortScan_Popup", "Specific ports"))
        self.portscan_standard_check.setText(_translate("PortScan_Popup", "Standard"))
        self.label_6.setText(_translate("PortScan_Popup", "Scan Type"))
        self.checkBox_2.setText(_translate("PortScan_Popup", "Other1"))
        self.checkBox_3.setText(_translate("PortScan_Popup", "Other2"))
        self.portscan_stealth_check.setText(_translate("PortScan_Popup", "Stealth"))
        self.portscan_start.setText(_translate("PortScan_Popup", "-->> Start Scan <<--"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'portscan_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PortScan_Popup(object):
    def setupUi(self, PortScan_Popup):
        PortScan_Popup.setObjectName("PortScan_Popup")
        PortScan_Popup.resize(350, 425)
        self.portscan_IP = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_IP.setGeometry(QtCore.QRect(50, 40, 250, 25))
        self.portscan_IP.setObjectName("portscan_IP")
        self.portscan_minport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_minport.setGeometry(QtCore.QRect(50, 100, 100, 25))
        self.portscan_minport.setObjectName("portscan_minport")
        self.portscan_maxport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_maxport.setGeometry(QtCore.QRect(200, 100, 100, 25))
        self.portscan_maxport.setObjectName("portscan_maxport")
        self.portscan_extraport = QtWidgets.QLineEdit(PortScan_Popup)
        self.portscan_extraport.setGeometry(QtCore.QRect(50, 190, 250, 25))
        self.portscan_extraport.setObjectName("portscan_extraport")
        self.label = QtWidgets.QLabel(PortScan_Popup)
        self.label.setGeometry(QtCore.QRect(50, 20, 66, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(PortScan_Popup)
        self.label_2.setGeometry(QtCore.QRect(50, 80, 66, 19))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(PortScan_Popup)
        self.label_3.setGeometry(QtCore.QRect(200, 80, 66, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(PortScan_Popup)
        self.label_4.setGeometry(QtCore.QRect(140, 140, 51, 19))
        self.label_4.setAutoFillBackground(False)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(PortScan_Popup)
        self.label_5.setGeometry(QtCore.QRect(50, 170, 301, 20))
        self.label_5.setObjectName("label_5")
        self.portscan_standard_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_standard_check.setGeometry(QtCore.QRect(50, 280, 92, 25))
        self.portscan_standard_check.setObjectName("portscan_standard_check")
        self.label_6 = QtWidgets.QLabel(PortScan_Popup)
        self.label_6.setGeometry(QtCore.QRect(140, 240, 161, 19))
        self.label_6.setObjectName("label_6")
        self.checkBox_2 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_2.setGeometry(QtCore.QRect(50, 310, 92, 25))
        self.checkBox_2.setObjectName("checkBox_2")
        self.checkBox_3 = QtWidgets.QCheckBox(PortScan_Popup)
        self.checkBox_3.setGeometry(QtCore.QRect(225, 310, 92, 25))
        self.checkBox_3.setObjectName("checkBox_3")
        self.portscan_stealth_check = QtWidgets.QCheckBox(PortScan_Popup)
        self.portscan_stealth_check.setGeometry(QtCore.QRect(225, 280, 92, 25))
        self.portscan_stealth_check.setObjectName("portscan_stealth_check")
        self.portscan_start = QtWidgets.QPushButton(PortScan_Popup)
        self.portscan_start.setGeometry(QtCore.QRect(50, 380, 251, 27))
        self.portscan_start.setObjectName("portscan_start")

        self.retranslateUi(PortScan_Popup)
        QtCore.QMetaObject.connectSlotsByName(PortScan_Popup)

    def retranslateUi(self, PortScan_Popup):
        _translate = QtCore.QCoreApplication.translate
        PortScan_Popup.setWindowTitle(_translate("PortScan_Popup", "PortScan"))
        self.portscan_IP.setPlaceholderText(_translate("PortScan_Popup", "8.8.8.8"))
        self.portscan_minport.setPlaceholderText(_translate("PortScan_Popup", "1"))
        self.portscan_maxport.setPlaceholderText(_translate("PortScan_Popup", "1024"))
        self.portscan_extraport.setPlaceholderText(_translate("PortScan_Popup", "80, 443"))
        self.label.setText(_translate("PortScan_Popup", "Target IP"))
        self.label_2.setText(_translate("PortScan_Popup", "Min Port"))
        self.label_3.setText(_translate("PortScan_Popup", "Max Port"))
        self.label_4.setText(_translate("PortScan_Popup", "And/Or"))
        self.label_5.setText(_translate("PortScan_Popup", "Specific ports"))
        self.portscan_standard_check.setText(_translate("PortScan_Popup", "Standard"))
        self.label_6.setText(_translate("PortScan_Popup", "Scan Type"))
        self.checkBox_2.setText(_translate("PortScan_Popup", "Other1"))
        self.checkBox_3.setText(_translate("PortScan_Popup", "Other2"))
        self.portscan_stealth_check.setText(_translate("PortScan_Popup", "Stealth"))
        self.portscan_start.setText(_translate("PortScan_Popup", "-->> Start Scan <<--"))
