# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 212)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_send_SHELL = QtWidgets.QPushButton(shell_SEND)
        self.popup_send_SHELL.setGeometry(QtCore.QRect(110, 150, 87, 27))
        self.popup_send_SHELL.setObjectName("popup_send_SHELL")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_send_SHELL.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 212)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_send_SHELL = QtWidgets.QPushButton(shell_SEND)
        self.popup_send_SHELL.setGeometry(QtCore.QRect(110, 150, 87, 27))
        self.popup_send_SHELL.setObjectName("popup_send_SHELL")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_send_SHELL.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 212)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_shell_SEND = QtWidgets.QPushButton(shell_SEND)
        self.popup_shell_SEND.setGeometry(QtCore.QRect(110, 150, 87, 27))
        self.popup_shell_SEND.setObjectName("popup_shell_SEND")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_shell_SEND.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 270)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_shell_SEND = QtWidgets.QPushButton(shell_SEND)
        self.popup_shell_SEND.setGeometry(QtCore.QRect(110, 210, 87, 27))
        self.popup_shell_SEND.setObjectName("popup_shell_SEND")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")
        self.popup_shell_SHELL = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_SHELL.setGeometry(QtCore.QRect(60, 170, 201, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.popup_shell_SHELL.setFont(font)
        self.popup_shell_SHELL.setObjectName("popup_shell_SHELL")
        self.label_3 = QtWidgets.QLabel(shell_SEND)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 201, 19))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(shell_SEND)
        self.label_4.setGeometry(QtCore.QRect(60, 150, 131, 19))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_shell_SEND.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
        self.label_3.setText(_translate("shell_SEND", "Shell to forward"))
        self.label_4.setText(_translate("shell_SEND", "EX: /bin/bash"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 270)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setText("")
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_shell_SEND = QtWidgets.QPushButton(shell_SEND)
        self.popup_shell_SEND.setGeometry(QtCore.QRect(110, 200, 87, 27))
        self.popup_shell_SEND.setObjectName("popup_shell_SEND")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")
        self.popup_shell_SHELL = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_SHELL.setGeometry(QtCore.QRect(60, 150, 201, 27))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.popup_shell_SHELL.setFont(font)
        self.popup_shell_SHELL.setObjectName("popup_shell_SHELL")
        self.label_3 = QtWidgets.QLabel(shell_SEND)
        self.label_3.setGeometry(QtCore.QRect(60, 130, 201, 19))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_shell_IP.setPlaceholderText(_translate("shell_SEND", "12.34.56.210"))
        self.popup_shell_PORT.setPlaceholderText(_translate("shell_SEND", "5555"))
        self.popup_shell_SEND.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
        self.popup_shell_SHELL.setPlaceholderText(_translate("shell_SEND", "/bin/bash, /bin/sh, etc"))
        self.label_3.setText(_translate("shell_SEND", "Shell to forward"))
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shell_popup.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_shell_SEND(object):
    def setupUi(self, shell_SEND):
        shell_SEND.setObjectName("shell_SEND")
        shell_SEND.resize(325, 270)
        font = QtGui.QFont()
        font.setPointSize(9)
        shell_SEND.setFont(font)
        self.popup_shell_IP = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_IP.setGeometry(QtCore.QRect(60, 30, 201, 27))
        self.popup_shell_IP.setText("")
        self.popup_shell_IP.setObjectName("popup_shell_IP")
        self.popup_shell_PORT = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_PORT.setGeometry(QtCore.QRect(60, 90, 201, 27))
        self.popup_shell_PORT.setObjectName("popup_shell_PORT")
        self.popup_shell_SEND = QtWidgets.QPushButton(shell_SEND)
        self.popup_shell_SEND.setGeometry(QtCore.QRect(110, 200, 87, 27))
        self.popup_shell_SEND.setObjectName("popup_shell_SEND")
        self.label = QtWidgets.QLabel(shell_SEND)
        self.label.setGeometry(QtCore.QRect(60, 10, 191, 19))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(shell_SEND)
        self.label_2.setGeometry(QtCore.QRect(60, 70, 141, 19))
        self.label_2.setObjectName("label_2")
        self.popup_shell_SHELL = QtWidgets.QLineEdit(shell_SEND)
        self.popup_shell_SHELL.setGeometry(QtCore.QRect(20, 150, 291, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.popup_shell_SHELL.setFont(font)
        self.popup_shell_SHELL.setObjectName("popup_shell_SHELL")
        self.label_3 = QtWidgets.QLabel(shell_SEND)
        self.label_3.setGeometry(QtCore.QRect(20, 130, 201, 19))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(shell_SEND)
        QtCore.QMetaObject.connectSlotsByName(shell_SEND)

    def retranslateUi(self, shell_SEND):
        _translate = QtCore.QCoreApplication.translate
        shell_SEND.setWindowTitle(_translate("shell_SEND", "Form"))
        self.popup_shell_IP.setPlaceholderText(_translate("shell_SEND", "12.34.56.210"))
        self.popup_shell_PORT.setPlaceholderText(_translate("shell_SEND", "5555"))
        self.popup_shell_SEND.setText(_translate("shell_SEND", "Send Shell!"))
        self.label.setText(_translate("shell_SEND", "IP Address of listener"))
        self.label_2.setText(_translate("shell_SEND", "Port of listener"))
        self.popup_shell_SHELL.setPlaceholderText(_translate("shell_SEND", "/bin/bash, c:\\\\Windows\\\\System32\\\\cmd.exe"))
        self.label_3.setText(_translate("shell_SEND", "Shell to forward"))
